// Code generated by MockGen. DO NOT EDIT.
// Source: wisun.go

// Package wisun is a generated GoMock package.
package wisun

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockSerial is a mock of Serial interface
type MockSerial struct {
	ctrl     *gomock.Controller
	recorder *MockSerialMockRecorder
}

// MockSerialMockRecorder is the mock recorder for MockSerial
type MockSerialMockRecorder struct {
	mock *MockSerial
}

// NewMockSerial creates a new mock instance
func NewMockSerial(ctrl *gomock.Controller) *MockSerial {
	mock := &MockSerial{ctrl: ctrl}
	mock.recorder = &MockSerialMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSerial) EXPECT() *MockSerialMockRecorder {
	return m.recorder
}

// Send mocks base method
func (m *MockSerial) Send(cmd string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", cmd)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send
func (mr *MockSerialMockRecorder) Send(cmd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockSerial)(nil).Send), cmd)
}
